my_string = input('В этом году я обучаюсь в: ')
print(my_string)
print(len(my_string))
print(my_string.upper())
print(my_string.upper().lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string.upper()[4])
