my_string = input('Напишите предложение: ')
print(my_string)
print(len(my_string))
print(my_string.upper())
print(my_string.upper().lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string.upper()[-1])
